### ISSUE TITLE
Can't move a completed task to another section in "Board View"

### ISSUE THREAD

**Issue by raggesilver** [alainm23/planify#632]
**Describe the bug**
Can't move a completed task to another section in the "Board View".

**To Reproduce**
1. Create a task
2. Set it as done
3. Try dragging it to another section in board view mode

**Expected behavior**
I expected to be able to move completed tasks to my "Done" section.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS or DE: Fedora 33 / Gnome 3.38
 - Version master (currently 2.6.1)
 
 ```
           ID: com.github.alainm23.planner
         Ref: app/com.github.alainm23.planner/x86_64/master
        Arch: x86_64
      Branch: master
      Origin: planner-origin
  Collection: 
Installation: user
   Installed: 175.6 MB
     Runtime: org.gnome.Platform/x86_64/3.36
         Sdk: org.gnome.Sdk/x86_64/3.36

      Commit: 2ce75238fb2b123e974d7ee8a377a99bf532f23735b8653c50f1c21852c30bdd
     Subject: Export com.github.alainm23.planner
        Date: 2020-12-24 19:59:41 +0000
 ```
