### ISSUE TITLE
Dragging a project in the side bar sometimes breaks

### ISSUE THREAD

**Issue by raggesilver** [alainm23/planify#633]
**Describe the bug**
Dragging a project in the side bar sometimes breaks and both the dragged sub-project and parent project disappear.

**To Reproduce**

Here's [a video of this bug](https://youtu.be/ToQ3-ptT_9U) (the choppy mouse movement is due to recording on Wayland).

**Expected behavior**
Smooth & bug-less drag-n-drop.

**Desktop (please complete the following information):**
 - OS or DE: Fedora 33 / Gnome 3.38
 - Version master (currently 2.6.1)
 
 ```
           ID: com.github.alainm23.planner
         Ref: app/com.github.alainm23.planner/x86_64/master
        Arch: x86_64
      Branch: master
      Origin: planner-origin
  Collection: 
Installation: user
   Installed: 175.6 MB
     Runtime: org.gnome.Platform/x86_64/3.36
         Sdk: org.gnome.Sdk/x86_64/3.36

      Commit: 2ce75238fb2b123e974d7ee8a377a99bf532f23735b8653c50f1c21852c30bdd
     Subject: Export com.github.alainm23.planner
        Date: 2020-12-24 19:59:41 +0000
 ```
