### ISSUE TITLE
Black border around every window

### ISSUE THREAD

**Issue by samyakbardiya** [alainm23/planify#808]
**Describe the bug**
There is a huge black border around the application window. I have tried both Flatpak and AUR version, both are having the same issue.

**To Reproduce**
Open the application.

**Expected behavior**
No black border, as shown in your screenshots.

**Screenshots**
 - [Planner Window](https://imgur.com/aqIeiOn), the black border around the window.
 - [Settings Window](https://imgur.com/TePSs7N), having extra black border.

**Desktop (please complete the following information):**
 - OS or DE: [Artix Linux](https://artixlinux.org/), using [dwm](https://dwm.suckless.org/)
 - Version: 2.7

**Additional context**
ask, if you need any.

**Comment by bitwave** [comment]
add in `~/.config/gtk-3.0/gtk.css`

```css
@import 'colors.css';

window decoration {
    box-shadow: none;
    margin: 1px;
}
```
